name: Deploy

on:
  release:
    types: [ published ]

permissions:
  contents: read
  actions: read

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set Secret yml file.
        run: |
          touch ./src/main/resources/secret.yml
          echo "${{ secrets.SECRETYML }}" > ./src/main/resources/secret.yml
          cat ./src/main/resources/secret.yml

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew bootJar
        shell: bash

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            ${{ secrets.DOCKERHUB_REPOSITORY }}:${{ github.event.release.tag_name }}
            ${{ secrets.DOCKERHUB_REPOSITORY }}:latest